stages:
  - build
  - test

build:linux:
  image: rust:latest
  stage: build
  script:
    - cargo build
  cache:
    paths:
      - cargo/
      - target/

build:redox:
  image: redoxos/redoxer:latest
  stage: build
  script:
    - redoxer build --verbose
  cache:
    paths:
      - cargo/
      - target/

test:linux:
  image: 'rust:latest'
  stage: test
  dependencies:
    - build:linux
  script:
    - cargo test

fmt:
    stage: test
    script:
        - rustup component add rustfmt-preview
        - ./fmt.sh -- --check
    allow_failure: true
